version: '2'
services:
  discovery:
    build: discovery
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    restart: unless-stopped
    links:
      - configuration
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  configuration:
    build: configuration
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  ui:
    build: ui
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    restart: unless-stopped
    links:
      - configuration
    ports:
      - 80:8080
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  passenger:
    build: passenger
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      DATABASE_USER: $DATABASE_USER
      DATABASE_PASS: $DATABASE_PASS
    restart: unless-stopped
    links:
      - configuration
      - passenger-database
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  passenger-database:
    image: mariadb:10
    expose:
      - 3306
    volumes:
      - passenger-data:/var/lib/mysql
    environment:
      MYSQL_USER: $DATABASE_USER
      MYSQL_ROOT_PASSWORD: $DATABASE_PASS
      MYSQL_DATABASE: passenger
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  trip:
    build: trip
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
        DATABASE_USER: $DATABASE_USER
        DATABASE_PASS: $DATABASE_PASS
    restart: unless-stopped
    links:
      - configuration
      - trip-database
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  trip-database:
    image: mariadb:10
    expose:
      - 3306
    volumes:
      - trip-data:/var/lib/mysql
    environment:
      MYSQL_USER: $DATABASE_USER
      MYSQL_ROOT_PASSWORD: $DATABASE_PASS
      MYSQL_DATABASE: trip
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  notification:
    build: notification
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      DATABASE_USER: $DATABASE_USER
      DATABASE_PASS: $DATABASE_PASS
    restart: unless-stopped
    links:
      - configuration
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  notification-database:
    image: mariadb:10
    expose:
      - 3306
    volumes:
      - notification-data:/var/lib/mysql
    environment:
      MYSQL_USER: $DATABASE_USER
      MYSQL_ROOT_PASSWORD: $DATABASE_PASS
      MYSQL_DATABASE: notification
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  driver:
    build: driver
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      DATABASE_USER: $DATABASE_USER
      DATABASE_PASS: $DATABASE_PASS
    restart: unless-stopped
    links:
      - configuration
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  driver-database:
    image: mariadb:10
    expose:
      - 3306
    volumes:
      - driver-data:/var/lib/mysql
    environment:
      MYSQL_USER: $DATABASE_USER
      MYSQL_ROOT_PASSWORD: $DATABASE_PASS
      MYSQL_DATABASE: driver
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  billing:
    build: billing
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      DATABASE_USER: $DATABASE_USER
      DATABASE_PASS: $DATABASE_PASS
    restart: unless-stopped
    links:
      - configuration
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  billing-database:
    image: mariadb:10
    expose:
      - 3306
    volumes:
      - billing-data:/var/lib/mysql
    environment:
      MYSQL_USER: $DATABASE_USER
      MYSQL_ROOT_PASSWORD: $DATABASE_PASS
      MYSQL_DATABASE: billing
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "10"

volumes:
  passenger-data:
  trip-data:
  notification-data:
  driver-data:
  billing-data: